// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormsByUserID = `-- name: CountFormsByUserID :one
SELECT COUNT(*) FROM forms
WHERE user_id = $1
`

func (q *Queries) CountFormsByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (
    name, description, user_id, status, schema, settings, share_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at
`

type CreateFormParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	UserID      int32          `json:"user_id"`
	Status      NullFormStatus `json:"status"`
	Schema      []byte         `json:"schema"`
	Settings    []byte         `json:"settings"`
	ShareUrl    pgtype.Text    `json:"share_url"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Status,
		arg.Schema,
		arg.Settings,
		arg.ShareUrl,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms
WHERE id = $1
`

func (q *Queries) DeleteForm(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteForm, id)
	return err
}

const getFormByID = `-- name: GetFormByID :one
SELECT id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at FROM forms
WHERE id = $1
`

func (q *Queries) GetFormByID(ctx context.Context, id int32) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormByShareURL = `-- name: GetFormByShareURL :one
SELECT id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at FROM forms
WHERE share_url = $1
`

func (q *Queries) GetFormByShareURL(ctx context.Context, shareUrl pgtype.Text) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByShareURL, shareUrl)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFormsByUserID = `-- name: ListFormsByUserID :many
SELECT id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at FROM forms
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFormsByUserID(ctx context.Context, userID int32) ([]Form, error) {
	rows, err := q.db.Query(ctx, listFormsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.Status,
			&i.Schema,
			&i.Settings,
			&i.ShareUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedFormsByUserID = `-- name: ListPublishedFormsByUserID :many
SELECT id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at FROM forms
WHERE user_id = $1 AND status = 'published'
ORDER BY created_at DESC
`

func (q *Queries) ListPublishedFormsByUserID(ctx context.Context, userID int32) ([]Form, error) {
	rows, err := q.db.Query(ctx, listPublishedFormsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.Status,
			&i.Schema,
			&i.Settings,
			&i.ShareUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    schema = COALESCE($4, schema),
    settings = COALESCE($5, settings),
    updated_at = NOW()
WHERE id = $1
RETURNING id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at
`

type UpdateFormParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Schema      []byte      `json:"schema"`
	Settings    []byte      `json:"settings"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, updateForm,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Schema,
		arg.Settings,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFormShareURL = `-- name: UpdateFormShareURL :one
UPDATE forms
SET share_url = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at
`

type UpdateFormShareURLParams struct {
	ID       int32       `json:"id"`
	ShareUrl pgtype.Text `json:"share_url"`
}

func (q *Queries) UpdateFormShareURL(ctx context.Context, arg UpdateFormShareURLParams) (Form, error) {
	row := q.db.QueryRow(ctx, updateFormShareURL, arg.ID, arg.ShareUrl)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFormStatus = `-- name: UpdateFormStatus :one
UPDATE forms
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, form_id, name, description, user_id, status, schema, settings, share_url, created_at, updated_at
`

type UpdateFormStatusParams struct {
	ID     int32          `json:"id"`
	Status NullFormStatus `json:"status"`
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) (Form, error) {
	row := q.db.QueryRow(ctx, updateFormStatus, arg.ID, arg.Status)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Status,
		&i.Schema,
		&i.Settings,
		&i.ShareUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
