// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package db

import (
	"context"
)

const countResponsesByFormID = `-- name: CountResponsesByFormID :one
SELECT COUNT(*) FROM responses
WHERE form_id = $1
`

func (q *Queries) CountResponsesByFormID(ctx context.Context, formID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countResponsesByFormID, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResponse = `-- name: CreateResponse :one
INSERT INTO responses (
    form_id, data, meta
) VALUES (
    $1, $2, $3
)
RETURNING id, form_id, data, meta, created_at
`

type CreateResponseParams struct {
	FormID int32  `json:"form_id"`
	Data   []byte `json:"data"`
	Meta   []byte `json:"meta"`
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, createResponse, arg.FormID, arg.Data, arg.Meta)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResponse = `-- name: DeleteResponse :exec
DELETE FROM responses
WHERE id = $1
`

func (q *Queries) DeleteResponse(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteResponse, id)
	return err
}

const deleteResponsesByFormID = `-- name: DeleteResponsesByFormID :exec
DELETE FROM responses
WHERE form_id = $1
`

func (q *Queries) DeleteResponsesByFormID(ctx context.Context, formID int32) error {
	_, err := q.db.Exec(ctx, deleteResponsesByFormID, formID)
	return err
}

const getResponseByID = `-- name: GetResponseByID :one
SELECT id, form_id, data, meta, created_at FROM responses
WHERE id = $1
`

func (q *Queries) GetResponseByID(ctx context.Context, id int32) (Response, error) {
	row := q.db.QueryRow(ctx, getResponseByID, id)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listResponsesByFormID = `-- name: ListResponsesByFormID :many
SELECT id, form_id, data, meta, created_at FROM responses
WHERE form_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResponsesByFormID(ctx context.Context, formID int32) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Data,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsesByFormIDPaginated = `-- name: ListResponsesByFormIDPaginated :many
SELECT id, form_id, data, meta, created_at FROM responses
WHERE form_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResponsesByFormIDPaginatedParams struct {
	FormID int32 `json:"form_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResponsesByFormIDPaginated(ctx context.Context, arg ListResponsesByFormIDPaginatedParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesByFormIDPaginated, arg.FormID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Data,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
