name: Trigger auto deployment for formify

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/formify-AutoDeployTrigger-1c61ecaa-66d6-4366-86be-505a455e35f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FORMIFY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FORMIFY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FORMIFY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          registryUrl: ${{ secrets.FORMIFY_REGISTRY_URL }}
          registryUsername: ${{ secrets.FORMIFY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FORMIFY_REGISTRY_PASSWORD }}
          containerAppName: formify
          resourceGroup: formify
          imageToBuild: ${{ secrets.FORMIFY_REGISTRY_URL }}/formify-server:${{ github.sha }}


